language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install codecov
  - pip install .
# command to run tests
script:
  - pytest
  - pytest --cov=tests/
after_success:
  - codecov