language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install codecov
  - pip install .

script:
  - pytest
  - pytest --cov=bitxchange tests/
after_success:
  - codecov