language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install coverage
  - pip install codecov
  - pip install .

script:
  - coverage run --source=bitxchange -m pytest
  - coverage report
after_success:
  - codecov